### ISSUE TITLE
OBA not showing service for RVTD

### ISSUE THREAD

**Issue by evantrillium** [Trillium-Solutions/oba_rvtd_deployer#1]
@ed-g received notice yesterday that Route 60 was not showing on OBA. I ran the Jenkins script rvtd_oba_fetch_new_gtfs and the app is now showing no service.

Last time this came up, you concluded with this:
I've added, and set up this monitor:

trigger: https://zabbix.trilliumtransit.com/zabbix/triggers.php?form=update&hostid=10283&triggerid=16637

web: https://zabbix.trilliumtransit.com/zabbix/httpconf.php?form=update&hostid=10283&httptestid=140

stop page url: http://oba.rvtd.org:8080/onebusaway-webapp/where/standard/stop.action?id=981_610080

You also noted last month on https://github.com/Trillium-Solutions/GTFSManager/issues/5900#issuecomment-897174969

for zabbix, had to add the ipv6 address of zabbix.trilliumtransit.com as an authorized source address. however that's not compatible with the version of zabbix on oba.rvtd.org (old amazon linux) so we may need to customize for that host.

**Comment by ed-g** [comment]
@arr0nax can you investigate please?

**Comment by ed-g** [comment]
@evantrillium we've been trying to add bug report templates to all repos but I missed this one. Can you include information from https://github.com/Trillium-Solutions/oba_rvtd_deployer/blob/master/.github/ISSUE_TEMPLATE/bug-report.md 

The main thing we're missing in this case is the ability to reproduce, a specific URL would be the best but not only way.

**Comment by ed-g** [comment]
Technically this is an operational issue which may or may not be due to a bug, but the information needed is more or less the same either way.

**Comment by ed-g** [comment]
Especially since the zabbix monitor is not showing any problems for oba. https://zabbix.trilliumtransit.com/zabbix/zabbix.php?action=dashboard.view

This implies that either we should add more monitoring, or it's possible the site is fine and the issue lies elsewhere.

**Comment by ed-g** [comment]
It looks like their calendar expired on the 12th.

```
service_id,sunday,monday,tuesday,wednesday,thursday,friday,saturday,start_date,end_date
86d5817d-c6d6-49cd-8adb-8f844340e55a,1,1,1,1,1,1,1,20210628,20210912
927d1f0d-3a34-40f4-9ab6-d318d802b719,0,1,1,1,1,1,0,20210628,20210912
8ccef2e7-69c1-4215-965f-e2143a5e8c5a,1,0,0,0,0,0,0,20210628,20210912
9944e758-a5cd-4655-925e-5eb546986695,0,0,0,0,0,0,1,20210628,20210912
[ec2-user@oba gt]$ 
```

**Comment by arr0nax** [comment]
Sorry, im late here. @ed-g do you think that is the cause? Should I still investigate?

**Comment by evantrillium** [comment]
there was a new dataset posted last week that contained service starting 9/13 - did my fetch not pull from the last dataset (see attached)
[rvtd-or-us.zip](https://github.com/Trillium-Solutions/oba_rvtd_deployer/files/7187579/rvtd-or-us.zip)

**Comment by ed-g** [comment]
They don't pull from our url, they pull from their own, 

export GTFS_LOCATION=http://feed.rvtd.org/googleFeeds/static/google_transit.zip

**Comment by ed-g** [comment]
@arr0nax I don't know for certain. We still need a URL to reproduce.

**Comment by arr0nax** [comment]
@ed-g it looks like the "OBA Arrivals" web test is missing from zabbix for some reason. 
https://zabbix.trilliumtransit.com/zabbix/httpconf.php?&hostid=10374

**Comment by ed-g** [comment]
Yeah I just saw that. Can you add it to the oba template as a web scenario?

**Comment by ed-g** [comment]
You can just copy the one from uptime robot

**Comment by arr0nax** [comment]
Done!

**Comment by ed-g** [comment]
I'm guessing this is p1, correct me if I'm wrong.

**Comment by ed-g** [comment]
@christrillium @evantrillium can one of you check with RVTD and see if they're aware that their calendars are expired? We don't know for certain if that's the problem but it's certainly possible.

Second, can you get a stop along the route for route 60 (preferably a stop-id, but a name is ok and we can lookup the stop-id from gtfs) then we can add a monitor for this so we can (a) know when this is fixed (b) detect if if happens next time.

**Comment by evantrillium** [comment]
@ed-g the calendars on the current data.trilliumtransit.com is up to date - do they need to update http://feed.rvtd.org/googleFeeds/static/google_transit.zip themselves?

**Comment by ed-g** [comment]
I don't know how they manage data at that zip or where it comes from. All I know is it's input to oba.

**Comment by evantrillium** [comment]
@ed-g what does this Jenkins task do
https://regression-testing.trilliumtransit.com/job/rvtd_oba_fetch_new_gtfs/

**Comment by ed-g** [comment]
And it's possible that it's used by whatever realtime arrival estimate they use to generate realtime feeds. I don't know that for a fact; it's just possible.

Jenkins task updates the gtfs, which happens nightly on an automatic basis anyway. It won't help if the data is wrong.

**Comment by evantrillium** [comment]
what does "updates the gtfs" mean - it pulls from data.trilliumtransit.com and puts it where?

**Comment by evantrillium** [comment]
what I'm getting at is that the public data my team posts at data.trilliumtransit.com contains active service calendars - there is no expiration at that feed.

So if it didn't make it to http://feed.rvtd.org/googleFeeds/static/google_transit.zip, and the Jenkins task doesn't manually send it to that location, then we need to ask RVTD how that URL gets updated.

**Comment by ed-g** [comment]
yes exactly. they need to sort out where their data comes from. I simply don't have that information.

The script on oba.rvtd.org doesn't do anything with data.trilliumtransit.com (sadly). It just pulls from their url and loads on the one bus away server.

**Comment by evantrillium** [comment]
perfect - understo
<img width="548" alt="Screen Shot 2021-09-17 at 1 09 25 PM" src="https://user-images.githubusercontent.com/31700284/133864067-dd0a83d4-48ab-4b48-be0c-a5e498aa3872.png">
od

**Comment by ed-g** [comment]
I don't know that their gtfs data has anything to do with ours although it might. for instance, they use different stop ids than we do. it could be that they run a script or operation with their realtime system to build gtfs from ours. or it could be a gtfs they produce themselves.

Where your diagram has a ??? there might or might not be an arrow.

**Comment by ed-g** [comment]
And jenkins arrow is 99.9% usually a cron job running from OBA server; I left the jenkins job lying around although we probably don't need it.

**Comment by evantrillium** [comment]
so it looks like it's their responsibility, per the ops manual

https://sites.google.com/trilliumtransit.com/trillium-operations/clients/rvtd?authuser=0
RVTD updates their GTFS and places it in the OneBusAway (OBA) fetch location, which fetches once daily late at night.

**Comment by ed-g** [comment]
yes it is. I just don't think they're aware that their calendars are expired. which is very likely the cause of this but of course we don't know 100%.

**Comment by evantrillium** [comment]
but that's the thing - they think their calendars are fine because they are in their public GTFS. They did lose their GTFS Manager user earlier this year, so it's possible that person was making that update and RVTD isn't aware that the public feed (unexpired) hasn't been migrated to their private GTFS (expired.)

**Comment by ed-g** [comment]
Which means RVTD might also not be aware that they used to make edits to the gtfs before posting. I don't know why their gtfs is different from ours or what the purpose of those edits were/are.

I guess if they really have no idea what data they are using or want to use I can just try pointing OBA at our gtfs and see what happens.

**Comment by ed-g** [comment]
If their realtime system has some kind of requirement for example, and using unedited gtfs didn't work in some circumstances. I'd be worried if no one did any investigation of that.

**Comment by ed-g** [comment]
Oh yeah just saw Matt's email. They totally changed realtime providers as well.

**Comment by ed-g** [comment]
@arr0nax note data sources in 

onebusaway-transit-data-federation-webapp/src/main/resources/data-sources.xml

**Comment by ed-g** [comment]
@evantrillium I've made some data updates based on Matt's email. But I don't know how to test. Can you ask them to test, or a stop_id that we can test at that should have arrivals right now?

**Comment by ed-g** [comment]
Hi @evantrillium good questions:

> @ed-g sorry to resurrect this - to confirm:
> 
>     1. Trillium has a server set up for RVTD that hosts a copy of their GTFS (however modified and drawn from a posted feed on their website) and GTFS-rt URLs

It turns out they stopped hosting or modifying their GTFS, so the GTFS now pulls from data.trilliumtransit.com.

And yes, that data is copied to oba.rvtd.org daily as part of the oba update process.

> 
>     2. Those GTFS-rt URLs were updated to draw from Engie, not their old TripSpark source, in this ticket

Yes precisely.

> 
>     3. We would assume the cost of calls from any consumer (such as OBA app) drawing on these URLs

I don't understand the question, can you clarify?

Do you mean calls like customer support calls, or calls like some program fetching data from one bus away? By OBA app do you mean the iphone/android app or the one bus away server application?

What is the underlying concern this question is intended to address?

> 
> 
> cc @christrillium

**Comment by evantrillium** [comment]
@ed-g I am trying to determine if we can deprecate this server/service for RVTD. It was established to address a previous gtfs-rt environment with no endpoints that could function in an application like OBA, so we built it to act as such.

Now that they have Engie, a new gtfs-rt producer, I would like to pass that responsibility onto Engie and get out of the gtfs-rt hosting responsibilities. OBA, and any other app like Transit, should direct api calls to Engie's servers, not ours.

Most CAD/AVL companies do not make their URLs public because of the cost of fielding the api calls from the apps, and I am concerned we could end up bearing the cost of those api calls.
