### ISSUE TITLE
looks like google api changed

### ISSUE THREAD

**Issue by ed-g** [Trillium-Solutions/oba_rvtd_deployer#3]
http://oba.rvtd.org:8080/onebusaway-webapp/ works.

http://oba.rvtd.org:8080/onebusaway-webapp/where/standard/ doesn't load, and some google api pages giving 404 so that may be the problem.

**Comment by lisaattrillium** [comment]
urgent enough to be in the next sprint? @ed-g

**Comment by ed-g** [comment]
It doesn't directly break the site, but makes it harder to test since you can't click on a map, you must instead enter id's after looking them up in the GTFS.

I wouldn't call it urgent, but it's not an issue we can ignore forever either.

**Comment by lisaattrillium** [comment]
plan in 11.1.0
action in 11.2.0
does that sound good?
@ed-g

**Comment by ed-g** [comment]
Our choice of solution also depends on what the sla with rvtd looks like.

So provided we have that, then yes.

**Comment by lisaattrillium** [comment]
@schurnsi can you check rvtd's sla? do we have billable time to work on this?

**Comment by ed-g** [comment]
They won't be using OBA after current contract finishes.
