### ISSUE TITLE
alerts feed for OBA

### ISSUE THREAD

**Issue by evantrillium** [Trillium-Solutions/oba_rvtd_deployer#4]
RVTD is trying to publish alerts to OBA and I want to confirm whether we included their alerts feed when it was updated in #1 

We rec'd these from RVTD at that time:
>GTFS-RT feeds from Engie:
>http://gtfsrt.rvtd.org:8085/ProfilGtfsRt2_0RSProducer-RVTD/Alert.pb
>http://gtfsrt.rvtd.org:8085/ProfilGtfsRt2_0RSProducer-RVTD/VehiclePosition.pb
>http://gtfsrt.rvtd.org:8085/ProfilGtfsRt2_0RSProducer-RVTD/TripUpdate.pb

was alerts included?

cc @ed-g

**Comment by lisaattrillium** [comment]
@schurnsi asked a similar question this afternoon too:

> Hi Ed,

> When you connected the Engie real-time feeds to OBA, do you happen to know if the service alerts feed was also connected?

> Thank you,

> Seth

**Comment by ed-g** [comment]
Yes, the url they gave us is 

http://gtfsrt.rvtd.org:8085/ProfilGtfsRt2_0RSProducer-RVTD/Alert.pb

Which looks like it matches.

**Comment by evantrillium** [comment]
so it sounds like it may be a configuration on oba's end. @ed-g to what degree to we have any role in maintaining further levels of configuration of the oba instance? are we just maintaining the server, or do we have further irons in that fire?

**Comment by schurnsi** [comment]
@evantrillium I'm working on an update to our contract here and will finalize it this week for RVTD.

It looks like the alert feed is a proper GTFS-realtime service alerts format, and that it is connected correctly to OBA, but we're not really sure how the OBA app displays alerts. For this one specifically, it was a route 1X alert only, so idk if we needed to have planned a trip on 1X for the alert show up or not. It also expired last night at midnight.

RVTD pays annual OBA support from Trillium, but we are working to get away from this. In fact, now that I've fully reviewed the legal contract, support actually should have ended or been renegotiated in June 2020 (it was a 5 year contract for Trapeze --> OBA). I'm pretty sure we should have been billing hourly support for the Engie change over, unfortunately.

Original Contracted Support Terms:

![Screen Shot 2022-01-03 at 1 24 06 PM](https://user-images.githubusercontent.com/7635869/147982556-a9f5baf4-d55e-4f21-b0ee-416a545c5622.png)
![Screen Shot 2022-01-03 at 1 24 39 PM](https://user-images.githubusercontent.com/7635869/147982561-d91ed50e-7d20-42ae-9693-bd817e165a79.png)

Out of Scope (billed hourly):
![Screen Shot 2022-01-03 at 1 25 57 PM](https://user-images.githubusercontent.com/7635869/147982635-4c07f484-4e8e-4f36-a23a-6c2d43d4e9be.png)
